### ISSUE TITLE
BindingsStream returned by queryBindings is not async iterable

### ISSUE THREAD

**Issue by zeroxbt** [comunica/comunica#1037]
#### Issue type:

- :bug: Bug 

____
#### Description:

BindingsStream is of type AsyncIterator but when I try to iterate over the returned values with a `for await`  loop, an error is thrown saying it is not async iterable.

____

**Comment by rubensworks** [comment]
`BindingsStream` is an [`AsyncIterator`](https://github.com/RubenVerborgh/AsyncIterator/), not an [async iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols).
So the `for await` operator is not supported (mainly due to it being slower than the operations provided by `AsyncIterator`).

It may be possible to make `for await` work in this case though, but that would require some changes in https://github.com/RubenVerborgh/AsyncIterator/.

**Comment by jeswr** [comment]
FWIW @zeroxbt  you can always use [this code](https://github.com/LDflex/LDflex-Comunica/blob/f01ece6fa8cee720061efd5ddd23ed82921555e4/src/ComunicaEngine.ts#L161-L215) to convert an [`AsyncIterator`](https://github.com/RubenVerborgh/AsyncIterator/), into an [async iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols).
