### ISSUE TITLE
xsd:dateTime doesn't work

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#1065]
#### Issue type:

- :bug: Bug 

____
#### Description:

Consider the following SPARQL query

```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>

SELECT *
WHERE {
  ?project a schema:Project;
           schema:endDate ?enddate.
  
  BIND(xsd:dateTime("2022-09-10"^^xsd:date) AS ?end)
}
```
The variable `?end` never gets a value assigned, while it should have the value `"2022-09-10"^^xsd:dateTime`.
____
#### Environment:
You find the query via the online client at
https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/follow-match-query/#datasources=https%3A%2F%2Fdata.knows.idlab.ugent.be%2Fperson%2Foffice%2Fprojects.ttl&query=PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Fproject%20a%20schema%3AProject%3B%0A%20%20%20%20%20%20%20%20%20%20%20schema%3AendDate%20%3Fenddate.%0A%20%20%0A%20%20BIND(%222022-09-10%22%5E%5Exsd%3AdateTime%20AS%20%3Fend)%0A%7D

**Comment by rubensworks** [comment]
This is either a problem in the bind actor, or in sparqlee.

**Comment by jeswr** [comment]
Related @pietercolpaert observed a while back that Comunica accepts negative `xsd:dateTime`s even though they are not allowed by the XSD spec.

In particular I *think* https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fquery.wikidata.org%2Fbigdata%2Fldf&query=PREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0ASELECT%20(count(%3Fperson)%20as%20%3Fcount)%20%3Fmonth%20%20WHERE%20%7B%0A%20%20%3Fperson%20wdt%3AP106%20wd%3AQ2066131%20%3B%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP569%20%3Fbirth%20.%0A%7D%0AGROUP%20BY%20(month(%3Fbirth)%20as%20%3Fmonth)&solidIdp=https%3A%2F%2Fpmcolpae.pod.knows.idlab.ugent.be%2F should fail because there are some invalid dates in the result and so the `month` function should error in some cases.

You can see the invalid dates as having the `type` `SPARQL_NON_LEXICAL` in https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fquery.wikidata.org%2Fbigdata%2Fldf&query=PREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0ASELECT%20DISTINCT%20(datatype(%3Fbirth)%20as%20%3Ftype)%20WHERE%20%7B%0A%20%20%3Fperson%20wdt%3AP106%20wd%3AQ2066131%20%3B%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP569%20%3Fbirth%20.%0A%7D%0A%20LIMIT%201000.

I think this comment should be a separate issue in SPARQLEE which I will open now as well.

**Comment by rubensworks** [comment]
@jitsedesmet Now that https://github.com/comunica/comunica/pull/1202 is merged, could you have a look to see if all problems raised in this issue are resolved? If so, we can close this issue.

**Comment by jitsedesmet** [comment]
If I am not mistaken, the important part of the query is the bind. This seems to be working now.
I run the query:
```sparql
PREFIX  ex:<http://example.com#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT * WHERE { 
?subject ex:hasDate ?date
BIND(xsd:dateTime("2022-09-10"^^xsd:date) AS ?end)
}
```

On dataset:
```
@prefix ex: <http://example.com#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject-date1 ex:hasDate "2022-10-11"^^xsd:date .
```

Results with: 
```
[
{"subject":"http://example.com#subject-date1","date":"\"2022-10-11\"^^http://www.w3.org/2001/XMLSchema#date","end":"\"2022-09-10T00:00:00\"^^http://www.w3.org/2001/XMLSchema#dateTime"}
]
```
This seems like the intended result?

**Comment by rubensworks** [comment]
Nice!
