### ISSUE TITLE
Blank nodes not serialized correctly in construct queries

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1160]
If I have the following `test.ttl` file containing one blank node:

```ttl
@prefix : <http://example.org/> .
:a :b [ :c :d ] .
```

Executing a construct query results in 2 blank nodes rather than the one

```bash
$ npx -p @comunica/query-sparql-file comunica-sparql-file ./test.ttl -q "CONSTRUCT WHERE { ?S ?P ?O }"
_:bc_0_n3-00 <http://example.org/c> <http://example.org/d>.
<http://example.org/a> <http://example.org/b> _:bc_0_n3-01.
```

Note that a select query correctly recognizes it as the same blank node

```bash
$ npx -p @comunica/query-sparql-file comunica-sparql-file ./test.ttl -q "SELECT * WHERE { ?S ?P ?O }"
[
{"S":"_:bc_0_n3-0","P":"http://example.org/c","O":"http://example.org/d"},
{"S":"http://example.org/a","P":"http://example.org/b","O":"_:bc_0_n3-0"}
]
```

**Comment by rubensworks** [comment]
Based on my understanding of the spec, this is how it should work.
Blank nodes should be scoped to a solution mapping. Since your query template has just a single triple pattern, each triple will be scoped to a separate solution mapping, so blank nodes will always be unrelated to each other.

This behaviour can be disabled in the context by setting `localizeBlankNodes` to `false`.

**Comment by namedgraph** [comment]
Jena does not agree :) Can we consult @afs or `public-sparql-dev@` here?
