### ISSUE TITLE
Make `FederatedQuadSource` just use a `UnionIterator`

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1166]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

See https://github.com/comunica/comunica/blob/490a687e7a5e25eda0c18ddd013a895898f4edff/packages/actor-rdf-resolve-quad-pattern-federated/lib/FederatedQuadSource.ts#L279
____

**Comment by rubensworks** [comment]
The reason why that workaround is needed, is because the federated iterator (`it`) could be destroyed before the lazy union iterator is started, in which case the `destroy` call will not be propagated to the sub-iterators, and they will be left un-destroyed.

See https://github.com/RubenVerborgh/AsyncIterator/issues/86

If this is clear, feel free to close this issue.
