### ISSUE TITLE
Migrate from cross-fetch to @inrupt/universal-fetch

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1195]
#### Issue type:

Both packages have the same goal of creating an isomorphic fetch function for browser and Node. Both packages behave the same in the browser (re-export the global fetch object) and in Node <=14 (where they export `node-fetch`).

In Node 16 @inrupt/universal-fetch uses https://www.npmjs.com/package/undici instead; which is the same package used to support native fetch in Node; and from Node 18+ @inrupt/universal-fetch exports the native fetch function. This allows for better support in Node 18+ where `node-fetch` doesn't behave to well and often requires the `Buffer` global to be polyfilled.

____

**Comment by rubensworks** [comment]
So the main difference between Inrupt's fetch and cross-fetch is that Inrupt's fetch uses undici in Node 16, while cross-fetch uses node-fetch in that case.

> This allows for better support in Node 18+ where node-fetch doesn't behave to well and often requires the Buffer global to be polyfilled.

I never encountered this problem tbh.

---

I've been thinking a bit about this, and I'm a bit hesitant to this change. As it's very invasive, and AFAIK, we have no open bug reports related to `fetch`, so AFAIK everything is working fine with `cross-fetch`.
So in the spirit of _don't touch what is not broken_, I'm a bit hesitant.
Because some other problems may arise by switching to a brand new package.
Nevertheless, I'm definitely open to it, if there would be some clear problems that are resolved by this.

**Comment by rubensworks** [comment]
FYI, cross-fetch v4 was released recently. It's unclear what the changes are exactly, but perhaps this update might fix your problems?
