### ISSUE TITLE
Comunica configuration files use invalid IRIs

### ISSUE THREAD

**Issue by pchampin** [comunica/comunica#1296]
#### Issue type:

- :bug: Bug 

____
#### Description:

Comunica configuration files, such as the one documented [here](https://comunica.dev/docs/modify/getting_started/custom_config_cli/#main-config-file), are invalid JSON-LD document :

* first, the context is expected to be an IRI, but the character '^' is used in the path. It should be escaped as %5E
* second, the IRIs expanded by the context also contain the (unescaped) character '^', so even a JSON-LD processor that would pass through the error above would produce RDF quads that contain invalid  IRIs (example [here](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Flinkedsoftwaredependencies.org%2Fbundles%2Fnpm%2F%40comunica%2Fconfig-query-sparql%2F%5E2.0.0%2Fcomponents%2Fcontext.jsonld%22%5D%2C%22%40id%22%3A%22urn%3Acomunica%3Amy%22%2C%22%40type%22%3A%22Runner%22%2C%22import%22%3A%5B%22ccqs%3Aconfig%2Fcontext-preprocess%2Factors.json%22%2C%22ccqs%3Aconfig%2Fcontext-preprocess%2Fmediators.json%22%2C%22ccqs%3Aconfig%2Fhttp%2Factors.json%22%2C%22ccqs%3Aconfig%2Fhttp%2Fmediators.json%22%2C%22ccqs%3Aconfig%2Finit%2Factors.json%22%2C%22ccqs%3Aconfig%2Foptimize-query-operation%2Factors.json%22%2C%22ccqs%3Aconfig%2Foptimize-query-operation%2Fmediators.json%22%2C%22ccqs%3Aconfig%2Fquery-operation%2Factors.json%22%2C%22ccqs%3Aconfig%2Fquery-operation%2Fmediators.json%22%5D%7D&context=%7B%7D))

This is not preventing Comunica to work, but this is preventing other tools to parse Comunica config files, which kills the purpose of them being based on JSON-LD...

____
#### Environment:

Not that it is relevant, but there it is:
```
> comunica-sparql -v
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.10.1 
| node             | v18.16.0
| npm              | 8.15.1
| yarn             | 1.22.5
| Operating System | linux (Linux 6.5.0-13-generic)
```

#### Crash log:

N/A

**Comment by rubensworks** [comment]
Indeed, you're right. This is a painful, but deliberate approach beyond the specs.

The reason why this was done is because `https://linkedsoftwaredependencies.org/bundles/npm/@comunica/config-query-sparql/^2.0.0/components/context.jsonld` is simply more readable and more easy to modify than `https://linkedsoftwaredependencies.org/bundles/npm/@comunica/config-query-sparql/%5E2.0.0/components/context.jsonld`.
Node.js developers understand the meaning of `^` really well, but `%5E` not so much.

A way to preprocess (context) IRIs would be a nice way to solve this problem.
In the long-term, Components.js config files editing should become more automated so that manual interactions are not needed anymore. Once we have that, the `^` vs `%5E` issue for developers will go away.

The `@` should probably also be encoded into `%40`...

**Comment by rubensworks** [comment]
@pchampin We should definitely be able to do that indeed!
Following up in https://github.com/LinkedSoftwareDependencies/Components-Generator.js/issues/125
