### ISSUE TITLE
Multi-source traversal yields zero results

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#1336]
## Works (same query on 2 individual pods)
- https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/solid-default/#datasources=https%3A%2F%2Fdrive.verborgh.org%2F&query=PREFIX%20schema%3A%20%3Chttps%3A%2F%2Fschema.org%2F%3E%0A%0ASELECT%20%3Fmovie%20WHERE%20%7B%0A%20%20%3Fmovie%20a%20schema%3AMovie.%0A%7D
- https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/solid-default/#datasources=https%3A%2F%2Ftimbl.com%2Ftimbl%2FPublic%2FTest%2F&query=PREFIX%20schema%3A%20%3Chttps%3A%2F%2Fschema.org%2F%3E%0A%0ASELECT%20%3Fmovie%20WHERE%20%7B%0A%20%20%3Fmovie%20a%20schema%3AMovie.%0A%7D

## Doesn't work (same query on both pods together)
- https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/solid-default/#datasources=https%3A%2F%2Fdrive.verborgh.org%2F;https%3A%2F%2Ftimbl.com%2Ftimbl%2FPublic%2FTest%2F&query=PREFIX%20schema%3A%20%3Chttps%3A%2F%2Fschema.org%2F%3E%0A%0ASELECT%20%3Fmovie%20WHERE%20%7B%0A%20%20%3Fmovie%20a%20schema%3AMovie.%0A%7D
### Log
```
Requesting https://drive.verborgh.org/
Requesting https://timbl.com/timbl/Public/Test/
Identified as file source: https://drive.verborgh.org/
Identified as file source: https://timbl.com/timbl/Public/Test/
Pruning 2 source-specific operations
```

**Comment by surilindur** [comment]
Out of curiosity, I went to check with the browser debugger, and it seems `ActorOptimizeQueryOperationPruneEmptySourceOperations` prunes both sources (pods) because neither has the `KeysQuerySourceIdentify.traverse` key in their context (hence the log message). Specifically, the algebra `operation.metadata.scopedSource` has no context entries (for the algebra that gets provided to the pruning actor).

The lack of the traverse flag/key on the sources happens with both one and multiple sources defined, but it only causes an issue with multiple sources because of the `UNION` over them that triggers the pruning.

I have no idea why the key is missing, though.

**Comment by rubensworks** [comment]
Good catch @surilindur, the traverse key missing from the sources is indeed a problem that causes the pruning actor to prune the operations.
[This actor](https://github.com/comunica/comunica-feature-link-traversal/blob/master/packages/actor-context-preprocess-set-defaults-link-traversal/lib/ActorContextPreprocessSetDefaultsLinkTraversal.ts) should be setting the key (either as query-level context or source-level context, unsure about that), but I'm not sure why that's not the case.

@surilindur Can you look into this one? I don't think it will require too much effort.

For reference, this pruning actor was introduced in the recent comunica v3 release, so this probably worked before.

**Comment by RubenVerborgh** [comment]
Great work, team!

**Comment by rubensworks** [comment]
The query now works again in the web client.
