### ISSUE TITLE
Missing service description for `SERVICE` endpoint

### ISSUE THREAD

**Issue by giacomociti** [comunica/comunica#1412]
I'm querying an in-memory store using a `SERVICE` clause to enrich the data:

```js
import { QueryEngine } from "@comunica/query-sparql";
import { Store } from "n3";

const myEngine = new QueryEngine();
const store = new Store();

store.addQuad('http://dbpedia.org/resource/CaMia_Hopson', 
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 
  'http://xmlns.com/foaf/0.1/Person');

const bindingsStream = await myEngine.queryBindings(`
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>

    SELECT * WHERE {
      ?s a foaf:Person .

      SERVICE <https://dbpedia.org/sparql> { 
        {
            SELECT * WHERE { ?s foaf:name ?o }
            #LIMIT 1       
        }
      }
    }
    ` , {
        sources: [store],
      });

for await (const binding of bindingsStream) {
    console.log(binding.toString());
}
```

It works fine with <https://dbpedia.org/sparql>, but fails using an endpoint with a broken service description (like <https://lindas.admin.ch/query> which, btw, should be [fixed soon](https://github.com/zazuko/trifid/issues/461)). In other issues, I see the suggestion to declare the `sparql` source type explicitly, but I don't know how to do it in this case because the data source is specified with the `SERVICE` keyword and not in the query context.

I would expect a data source specified with the `SERVICE` keyword to be recognized as a SPARQL endpoint with no need to probe its service description.

Thanks for your help

**Comment by rubensworks** [comment]
> I see the suggestion to declare the sparql source type explicitly, but I don't know how to do it in this case because the data source is specified with the SERVICE keyword and not in the query context.

That won't be possible indeed. That's only possible when defining sources in the query context.

> I would expect a data source specified with the SERVICE keyword to be recognized as a SPARQL endpoint with no need to probe its service description.

The problem is that Comunica is a bit more liberal wrt to the spec, and also allows other types of sources to be queried using SERVICE keywords (e.g. TPF, Linked Data documents, ...). Comunica therefore has to determine source types on-the-fly.

Note that we do have a config option [`forceSparqlEndpoint`](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-service/lib/ActorQueryOperationService.ts#L76-L80C3) to enforce strict spec compliance, and always assume SPARQL endpoints here.
This is a config-level option, so it will require the creation of a custom engine config.
If this would not be a good solution for you, we can also consider adding a context-level option for this, so it can be passed to the engine together with the query and sources.

**Comment by giacomociti** [comment]
Thanks for the exhaustive answer, and the config-level option should be enough to solve my issue.

**Comment by rubensworks** [comment]
Ok, great! Do let me know if you need any help.
This tutorial might help in any case: https://comunica.dev/docs/modify/getting_started/custom_config_app/
