### ISSUE TITLE
Can ActorHttpNodeFetch become the default?

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#316]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

We should be using `fetch`. Can we test that this is possible in Node and the browser, and does not cause any performance differences?

Related: https://github.com/comunica/comunica/issues/313#issuecomment-435674629

**Comment by joachimvh** [comment]
Did some tests, from the queries I tried the fetch implementation is still about 20% slower. This could potentially be due to us using the isomorphic-fetch library. That library hasn't been updated in 3 years and internally makes use of node-fetch `^1.0.1`, while node-fetch is currently already at version 2.3.0. I tried looking into quickly changing to node-fetch in the comunica code  so I could do a quick comparison but there are interface differences which cause this to be a more drastic change than expected.

**Comment by RubenVerborgh** [comment]
Can’t we webpack the difference away?

**Comment by rubensworks** [comment]
@joachimvh Was this performance difference present in Node, the browser, or both? (I assume browser will be faster than Node)

> I tried looking into quickly changing to node-fetch in the comunica code so I could do a quick comparison but there are interface differences which cause this to be a more drastic change than expected.

Can you make a separate issue for this? And if isomorphic-fetch is so outdated, we should either update it ourselves if they accept PRs, or implement our own variant.

> Can’t we webpack the difference away?

I think @joachimvh means that the actual fetch API has been changed a bit, so I don't think we can fix this with Webpack, and this would still cause problems in Node.

**Comment by RubenVerborgh** [comment]
> > Can’t we webpack the difference away?
> 
> I think @joachimvh means that the actual fetch API has been changed a bit

I meant webpacking the performance difference away. I know that either node-fetch or isomorphic `fetch` actually go _beyond_ the browser's `fetch` API. But if you only rely on the browser `fetch` API, you shouldn't notice any difference.

**Comment by rubensworks** [comment]
Now that we have a dedicated [solid auth actor](https://github.com/comunica/actor-http-solid-auth-fetch), I guess this can be closed @RubenVerborgh?

I would stick with our native HTTP actor for now, until `isomorphic-fetch` is updated, or we use some alternative lib.
