### ISSUE TITLE
Select actor based on the metadata in each HTTP response

### ISSUE THREAD

**Issue by pietercolpaert** [comunica/comunica#432]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

![comunica-next-tree-qpf](https://user-images.githubusercontent.com/347073/55078913-771c3100-509b-11e9-9ebf-a87b44f2b4d1.png)

When designing Linked Data hypermedia Web APIs, we want to make sure any combination of interfaces becomes possible. E.g.:
 * a hydra Partial Collection View could trigger a next page actor,
 * the metadata gets interpreted again on the next page, and again a next page is followed
 * then a tree ontology description is given where a geospatial relation is provided
 * In worst case, your query does not provide any FILTER, and all links in this tree need to be followed. When a FILTER is given, potentially a part of the tree can be pruned.
 * When Comunica then encounters the QPF template, the QPF actor must be activated

This requires a slight refactor of how sources are identified. A source type needs to be scoped to 1 HTTP response. This way, an HTTP response of a request that happened inside a next page actor can again pass by the mediator that picks whether for the next step, the next page actor really is the best choice or not.

Another supporting use case is dynamic feature throttling by open data servers. When more/less load  is perceived on a server, fewer/more features can be offered automatically. When in the middle of a long query, your query processing will dynamically choose the right strategy and will not stop the query processing.

This feature has a dependency on feature request #121

**Comment by rubensworks** [comment]
With these latest commits, source types don't exist anymore. You can still pass them to _force_ a specific source type. For example, passing `file` as source will make sure that all hypermedia controls are ignored. Otherwise, controls are interpreted on _all_ sources.

Note that RDFJS sources always need to be forced using the `rdfjsSource` type.

This has been implemented and tested with the following sources:

* https://linked.open.gent/parking?page=2019-07-04T08:00:00
* https://graph.irail.be/sncb/connections
* https://query.wikidata.org/bigdata/ldf
* http://fragments.dbpedia.org/2016-04/en
* https://ruben.verborgh.org/profile/
* http://dbpedia.restdesc.org/

The only thing that still needs some work is handling of SPARQL endpoint, which will require interpreting service descriptions.

**Comment by rubensworks** [comment]
Not to self: Virtuoso seems to expose service descriptions via RDFa only, so #138 will be a prerequisite for this.
