### ISSUE TITLE
Improve definition of sources in comunica-sparql-http

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#433]
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

Currently, sources have to defined in a verbose way when setting up a SPARQL endpoint:

```
comunica-sparql-http "{ \"sources\": [{ \"type\": \"hypermedia\", \"value\" : \"http://fragments.dbpedia.org/2015/en\" }]}"
```

We should allow a way to define sources in the same way as `comunica-sparql`:

```
comunica-sparql-http http://fragments.dbpedia.org/2015/en
```

The context-based option should still be possible by using the `-c` option.

**Comment by FlorianFV** [comment]
To create a function for reading in the commandline arguments for comunica-sparql and comunica-sparql-http, an overview:

Common:

-c: contextobject specified by user
-l: the loggerlevel
--help: print helpmessage

Colliding:

-t: 	query: MIME-type output		http: query execution timeout
-p: 	query: delegates to given proxy	http: port number
-i:	query: query input format	        http: cache invalidation before each query

Only query:

-q: evaluate query
-f: evaluate query in file
-b: base IRI for query
-d: datetime Memento
--lenient: failing request logging instead of hard crash
--listformats: MIME-types
--version: version information

Another question:
The key of the sources in the context objects is in both cases different ('sources' in http,
'@comunica/bus-rdf-resolve-quad-pattern:sources' in query). So I wonder if I can just use the same 
same key values for the extra arguments if I support them in http as they are used in query.

**Comment by rubensworks** [comment]
Thanks for the overview @FlorianFV.
I would suggest the following:

## Common

-c: contextobject specified by user
-l: the loggerlevel
--help: print helpmessage

## Colliding

These clash indeed, but should only be relevant in their own context.
So I would handle these args in query and http separately (so not part of the abstracted method).

-t: query: MIME-type output http: query execution timeout
-p: query: delegates to given proxy http: port number
-i: query: query input format http: cache invalidation before each query

## Currently only query, but also add to http

-b: base IRI for query
--lenient: failing request logging instead of hard crash
--version: version information

## Only query

-q: evaluate query
-f: evaluate query in file
-d: datetime Memento
--listformats: MIME-types

-----

Do you agree that these make sense?

**Comment by FlorianFV** [comment]
I do agree that these make sense. @rubensworks 

Does it suffice to add the key value pairs of the b and lenient argument to the context?
Will these arguments be taken in consideration when the context is used, or do I need to add code for that too somewhere?

**Comment by rubensworks** [comment]
> The key of the sources in the context objects is in both cases different ('sources' in http,
'@comunica/bus-rdf-resolve-quad-pattern:sources' in query). So I wonder if I can just use the same
same key values for the extra arguments if I support them in http as they are used in query.

'sources' is a shortcut, so you should be able to use that instead.

> Does it suffice to add the key value pairs of the b and lenient argument to the context?

I would just do what the query CLI is already doing with those at the moment. (see `ActorInitSparql` class)
