### ISSUE TITLE
Random integration failure on rdfjs-information03

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#537]
#### Issue type:

- :bug: Bug

____
#### Description:

https://travis-ci.org/comunica/comunica/jobs/593534662#L1216

Not sure yet whether this is a Comunica bug or an rdf-test-suite-ldf bug.

**Comment by rubensworks** [comment]
Happened again here: #549

**Comment by rubensworks** [comment]
Also in #550 and #551.

**Comment by rubensworks** [comment]
@joachimvh If you find some time, could you have a look at this one?

It looks like for some reason the N3Store in the (rdfjs) integration tests is sometimes empty.
Since the queries are similar other integration tests that don't break, I don't think Comunica is at fault here, so it must either be caused by N3 or rdf-test-suite-ldf.

\cc @RubenVerborgh

**Comment by joachimvh** [comment]
Should be fixed in comunica/rdf-test-suite-ldf.js#28

I'm also wondering about [this](https://github.com/comunica/rdf-test-suite-ldf.js/blob/master/lib/testcase/ldf/LdfTestCaseEvaluationHandler.ts#L199) line. It always fails, since it checks if the test file exists in the local directory, while 1 line further it gets created in the temp directory using Path.join. But if the check happens with Path.join, the tests will fail if 2 of them use a data file with the same name but different contents (which is the case for the RDFJS test run). So not sure what the point is there.

Side note: in the same class I removed all references to the responseMocker causing the tests to run much faster. I assume it is needed in some cases (when the cache isn't filled/used?), but it would be nice to make sure it is only used when necessary because the performance difference is quite noticeable.

**Comment by rubensworks** [comment]
@ManuDeBuck Do you think what @joachimvh describes could be a bug? Or it this intentional?

**Comment by ManuDeBuck** [comment]
@joachimvh The first point you mention seems correct. This is indeed a mistake (don't know why I didn't notice this earlier on). It will indeed be problematic when using `Path.join`. It seems thus rather difficult to cache files via this way? I'll think about how we can fix this to make caching possible somehow.

I think I don't really understand your second point. Do you mean you eliminated the usage of the `responseMocker` - so running the tests without any mocked files? Because I don't think that's what we want `rdf-test-suite-ldf.js` to do. If I understand you correctly you mean that you won't be mocking any of the the requests at all. If the resources used by the tests change overtime (which most of them eventually will do) the tests may possibly fail - and this bug would be difficult to find. What I do think is that the usage of the `responseMocker` can be limited to only those tests who need the `responseMocker` (because, indeed, not all tests do). When I find some time in the future I'll maybe have a look.

**Comment by joachimvh** [comment]
For the caching, it might be interesting to not strip the folder of the data file, since the combination of folder + file will all be unique (when all your tests are in 1 repo at least).

Ah, it could be that specifically the tests I ran are those that didn't need the responsemocker (I only tested on the RDFJS tests since the original bug was situated there). But I noticed that those tests didn't make use of the responsemocker and I could drastically speed up my tests by just removing its instantiation.
