### ISSUE TITLE
Two-pattern queries broken when not using federated actor

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#566]
#### Issue type:

- :bug: Bug

____
#### Description:

The following query

```sparql
SELECT ?label WHERE {
  <https://ruben.verborgh.org/profile/#me> <http://xmlns.com/foaf/0.1/knows> ?v0.
  ?v0 <http://www.w3.org/2000/01/rdf-schema#label> ?label.
}
```

over `https://ruben.verborgh.org/profile/` only works with the federated actor. When passing a single `source`, it fails. The query with just one triple pattern works fine.

____
#### Environment:
```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.9.4
| node                | v12.6.0
| npm                 | 6.9.0
| yarn                | 1.17.3
| Operating System    | darwin (Darwin 18.6.0)
```

**Comment by rubensworks** [comment]
On the one hand, the single-source context entry is not part of the public API, so it may lead to undefined behaviour.

On the other hand, AFAIK this should not make any difference on this level. This should work, and may be a bug indeed.

**Comment by joachimvh** [comment]
I had a look at this, the problem seems to be the different ways how metadata gets handled in Comunica. As can be seen [here](https://github.com/comunica/comunica/blob/master/packages/bus-rdf-resolve-quad-pattern/lib/ActorRdfResolveQuadPatternSource.ts#L103-L104) and [here](https://github.com/comunica/comunica/blob/master/packages/bus-rdf-resolve-quad-pattern/lib/ActorRdfResolveQuadPatternSource.ts#L62-L71), the quad pattern resolver superclass requires the resulting source to emit a `metadata` event when it has the metadata. Now, the federated actor does this (which was part of the problem in #553 ) but the [single source actor](https://github.com/comunica/comunica/blob/master/packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedLinkedRdfSourcesAsyncRdfIterator.ts) does not.

This also explains why it works with 1 pattern since the metadata is not required there, while it is required for 2+ patterns (to determine which one to query first).

**Comment by rubensworks** [comment]
> Now, the federated actor does this (which was part of the problem in #553 ) but the single source actor does not.

The single source actor you link constructs sources using the `actor-rdf-resolve-hypermedia-*` actors. These should emit metadata events in the same way.
