### ISSUE TITLE
Comunica not following next page links

### ISSUE THREAD

**Issue by mielvds** [comunica/comunica#675]
#### Issue type:

- :question: Question

____
#### Question:

Not sure whether the issue is caused by Comunica, an underlying library, or the LD source (Web page with JSON-LD scripted in), so I added this as a question.

The following setup does not seem to follow any next page links:
`
comunica-sparql https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/ge%C3%AFllustreerde-zondagsgazet-familieblad/Q2QdWIVqWlyVTMJip6LgngZw "PREFIX schema:<http://schema.org/> SELECT ?uri  WHERE { GRAPH ?g { ?uri ?p schema:CreativeWork. } }"
`

When running `comunica-sparql https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/vooruit-socialistisch-dagblad/GegTRSIdRRTlJQT2daevtaql "PREFIX schema:<http://schema.org/> SELECT ?uri WHERE { GRAPH ?g { ?uri ?p schema:CreativeWork.}}"`, however, next page links are followed as expected. Page structure seems the same though.

(also putting @brechtvdv in the loop for maybe knowing some differences in the JSON-LD)

**Comment by rubensworks** [comment]
This seems to be a server issue caused by character encoding.

The requested URL is `https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/ge%C3%AFllustreerde-zondagsgazet-familieblad/Q2QdWIVqWlyVTMJip6LgngZw` (note the `%C3%AF`).
In order to determine metadata, Comunica will look for this URL in the response.
However, the page only contains metadata about `https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/geïllustreerde-zondagsgazet-familieblad/Q2QdWIVqWlyVTMJip6LgngZw` (note the `ï`).
As this is a different URL, Comunica will not find the metadata.

Two solutions are possible here:
1. The server applies a redirect for such encoded URLs to some canonical URL.
2. The server exposes metadata based on the requested URL (this is what LDF server does), so there may be different representations possible for the same data.

I believe @brechtvdv already reported this problem.

**Comment by mielvds** [comment]
Wow, good catch! Annoying side effect of URI --> IRI.  Since the data is pretty static, we'll go for option 1 if ever needed.

**Comment by mielvds** [comment]
Sorry, one more thing. ` comunica-sparql https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/geïllustreerde-zondagsgazet-familieblad/Q2QdWIVqWlyVTMJip6LgngZw "PREFIX schema:<http://schema.org/> SELECT ?uri ?o  WHERE { GRAPH ?g { ?uri a schema:CreativeWork} }" -l info` works now indeed. All URIs show up. Next page links are followed, page 2 in this case is https://nieuwsvandegrooteoorlog.hetarchief.be/nl/media/het-vaderland-belgisch-dagblad-te-havre-verschijnend/Q2QgOUQSUAFZIvEQrTsRQEjb

Strangely, however, when adding another binding to the query, for instance ` SELECT ?uri ?title  WHERE { GRAPH ?g { ?uri a schema:CreativeWork; dcterms:title ?title} }` , only the first page produces results, while technically, it has enough info to produce at least one binding for `?title` per `?uri` per page. Is it somehow waiting for all data to be collected to do the necessary joins?

**Comment by rubensworks** [comment]
> Is it somehow waiting for all data to be collected to do the necessary joins?

With the default BGP algorithm, the cardinality of the first triple pattern will be resolved first, which causes all pages to be traversed before any results will be emitted.

Other BGP algorithms would probably work better in this case. I have a WIP BGP algorithm for link traversal that would probably be usable for this. But nothing ready to use at the moment unfortunately.
