### ISSUE TITLE
Timeout on SPARQL queries

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#745]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

In our user-facing application, we would like to stop waiting for SPARQL responses if they take longer than a couple of seconds to arrive. While this can be solved in the calling code, it would be nice if Comunica supported client timeouts out of the box.

**Comment by rubensworks** [comment]
For reference, we've just implemented timeout support when running Comunica as a SPARQL endpoint (#797).

For direct usages of Comunica via the JS API, this might be more difficult, as it's not really possible to interupt a function call in a purely single-threaded JS environment.
So if we want to add this, we may want to create a webworker-based wrapper around Comunica, which can create one or more workers for executing a query, and killing such a worker one a timeout is exceeded.
Since inter-worker communication may be expensive, we'll have to investigate if it's feasible to pipe all query results across this worker communication API at a sufficient level of efficiency.

**Comment by rubensworks** [comment]
Considering this resolved (#70)
