### ISSUE TITLE
Query on http://dbpedia.org/sparql/ results in more than 40+ requests

### ISSUE THREAD

**Issue by danielbeeke** [comunica/comunica#758]
#### Issue type:

- :bug: Bug 

____
#### Description:

Query to dbpedia sparql endpoints results in a lot of requests.

Code example: https://gist.github.com/danielbeeke/c8f737269dbae2e3722d7b22329f57fd
Screenshot of the network inspector: https://imgur.com/a/NhjtIuX

**Comment by rubensworks** [comment]
I first thought this was the same as #609, but your code shows that you indicate the source with type `sparql`. So it _should_ indeed only do a single HTTP request. So something must be going wrong there indeed.

**Comment by danielbeeke** [comment]
How would I start debugging this?

I see for example that AsyncIteratorJsonBindings is within the deprecated module: 'actor-rdf-resolve-quad-pattern-sparql-json'.
I have put a debugger inside this module and see that it passes through it. 

Is there some kind of developer documentation of how to debug?
I am a bit clueless where to start, sorry.

**Comment by rubensworks** [comment]
The problem is that `actor-query-operation-sparql-endpoint` is for some reason not being invoked,
while it should be invoked if there's a single SPARQL endpoint source, as it can do some optimizations in that case.
Instead, `actor-rdf-resolve-hypermedia-sparql` is being invoked deeper down the pipeline, which is wrong here/

This page may also help: https://comunica.dev/docs/modify/advanced/architecture_sparql/

**Comment by danielbeeke** [comment]
A somehow I missed that documentation. Looks great, thank you!
I will try coming weeks to debug it.

**Comment by rubensworks** [comment]
Great! Be sure to let me know if you need further pointers.

**Comment by danielbeeke** [comment]
This issue seems to be in the wrong repo.
The issue only seems be triggered when using LDflex.

**Comment by danielbeeke** [comment]
I am sorry, after running npm update it seemed to be working.
