### ISSUE TITLE
suboptimal triple-pattern query plan when using FILTER

### ISSUE THREAD

**Issue by rooterkyberian** [comunica/comunica#834]
#### Issue type:

- :snail: Performance issue 

____
#### Description:

query:
```
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?company ?predicate ?value WHERE {
  ?company wdt:P31/wdt:P279* wd:Q4830453 .
  ?company ?predicate ?value .
  FILTER (?predicate in (rdfs:label, schema:description, skos:altLabel))
  FILTER (LANG(?value)="en")
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
```
source: https://query.wikidata.org/bigdata/ldf

seems like to me like optimal plan for this query would be to
1) figure out all subclasses (wdt:P279) of wd:Q4830453
2) search for all instances of (wdt:P31) subclasses we got
3) query for all instances (i.e. only by subject grabbing all predicate&objects associated with it) and do rest of processing in memory

the 1&2 seems to be done, but then comunica is doing "?company ?predicate ?value" i.e. calling https://query.wikidata.org/bigdata/ldf without any filters

I'm new to this but:
a) how can I view the execution plan ?
b) influence it so doesn't try to do a plan which involve 1e8 queries, but just the one I suggested above, which should be in order of 1e8 queries (3 orders of magnitude smaller)

____
#### Environment:

```
$ comunica-sparql -v
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.21.3 
| node                | v10.15.3
| npm                 | 7.14.0
| yarn                | 1.21.1
| Operating System    | linux (Linux 5.4.0-74-generic)
```

**Comment by rubensworks** [comment]
I suspect the property path is at the root cause of this performance issue, which would make it similar to #725.

> a) how can I view the execution plan ?

Due to the adaptive nature of Comunica, there's no straightforward way atm to view a query plan. (#210 would be needed for this)

At the moment, emitting debug logs in the respective actors can help.

> b) influence it so doesn't try to do a plan which involve 1e8 queries, but just the one I suggested above, which should be in order of 1e8 queries (3 orders of magnitude smaller)

This would require additional implementation effort, probably via a combination of #427 and #552.
Pinging @sroze as he was also interested in something similar.

**Comment by rooterkyberian** [comment]
wait, but there is a "plan" right? does comunica actually consider different version of "plan" and cost of executing it before/during running the query?

#210 talks about more about something that looks like profiling tool  than "here is how I think is how I PLAN TO execute this query".

**Comment by rubensworks** [comment]
> wait, but there is a "plan" right? does comunica actually consider different version of "plan" and cost of executing it before/during running the query?

There is a plan in the form on an algebra object.
Since all optimization of the algebra happens adaptively at runtime based on cardinality estimates, there is minimal preprocessing.
Nevertheless, everything is in place to add components to perform optimization before query execution as well, this just hasn't been implemented yet.

> #210 talks about more about something that looks like profiling tool than "here is how I think is how I PLAN TO execute this query".

Indeed, due to the adaptive nature of our query planning (required for enabling queries over heterogeneous sources), the final query plan can only be shown after query exec ends.

**Comment by rubensworks** [comment]
@rooterkyberian performance may be better in Comunica 2. Could you try again?
