### ISSUE TITLE
Superfluous warnings when installing comunica package

### ISSUE THREAD

**Issue by LaurensRietveld** [comunica/comunica#842]
#### Issue type:

- :bug: Bug 

____
#### Description:

When installing the latest comunica version, you'll get around 70 lines like this:

```
warning @comunica/actor-init-sparql > @types/rdf-js@4.0.2: This is a stub types definition. rdf-js provides its own type definitions, so you do not need this installed.
```

To reproduce:

```
mkdir test && cd test
yarn init -y 
yarn add @comunica/actor-init-sparq
```

____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.21.3 
| node                | v12.22.2
| npm                 | 6.14.13
| yarn                | 1.22.5
| Operating System    | linux (Linux 5.8.0-59-generic)

```

**Comment by rubensworks** [comment]
That's because of the recent transition of the types to https://github.com/rdfjs/types/
It will require quite a bit of effort to update Comunica and all its dependencies to this new package.

Since another big (and possibly breaking) change is [coming soon](https://github.com/rdfjs/types/pull/23), I'm postponing this update a bit, as to not have to go through this gargantuan effort twice.

**Comment by rubensworks** [comment]
Done in dfb903079605ce898f7206b0125eb60e89f993c8.

(I expect to do a new release later this month or early next month, lots of internal improvements happening)
