### ISSUE TITLE
Performance: use of `wrap` on RDFJS sources

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#965]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

After looking into [this issue](https://github.com/RubenVerborgh/AsyncIterator/issues/44), I suspect that the use of `wrap` (instances given below) within the engine is creating a significant overhead; especially for RDFJS sources, due to the fact that the buffer of elements may be quite large and then `Array.Shift` will cause a large overhead in Chrome/Nodejs. Whilst I would also recommend investigating `wrap` [upstream](https://github.com/RubenVerborgh/AsyncIterator) (perhaps `wrap` just return the original iterator if a `.read` method exists?); I think it is worth avoiding the use of `wrap` on sources that support async iteration . For instance, can you asynchronously iterator over results from QuadStore @jacoscaz ?

https://github.com/comunica/comunica/blob/4c66bfaa44f73786bc7403504e5fe571181430c7/packages/actor-rdf-resolve-quad-pattern-rdfjs-source/lib/RdfJsQuadSource.ts#L29
https://github.com/comunica/comunica/blob/4c66bfaa44f73786bc7403504e5fe571181430c7/packages/actor-rdf-resolve-hypermedia-sparql/lib/RdfSourceSparql.ts#L134
https://github.com/comunica/comunica/blob/4c66bfaa44f73786bc7403504e5fe571181430c7/packages/actor-rdf-resolve-hypermedia-qpf/lib/RdfSourceQpf.ts#L56

**Comment by jacoscaz** [comment]
@jeswr in Quadstore I use a custom `AsyncIterator` that wraps the `AbstractIterator` instance returned by the LevelDB backend: https://github.com/belayeng/quadstore/blob/2a538b729df63351dc587bc15b83cc7283cba9d2/lib/get/leveliterator.ts#L14

The other custom `AsyncIterator` I use is the sorting iterator, to which I am passing a `source` iterator via its constructor: https://github.com/belayeng/quadstore/blob/2a538b729df63351dc587bc15b83cc7283cba9d2/lib/get/sortingIterator.ts#L25

However, RDF/JS `Source` implementations support async iterator (and backpressure) by definition as their methods return RDF/JS `Stream` instances. The wrapping, I believe, is happening because in Comunica we're using prototype-based convenience methods (`AsyncIterator#map()`, ...) and, critically, `AsyncIterator`'s [properties feature](https://github.com/RubenVerborgh/AsyncIterator#setting-and-reading-properties).

Can we replace `wrap` with a simple custom `AsyncIterator` that skips buffering?

**Comment by jeswr** [comment]
> Can we replace wrap with a simple custom AsyncIterator that skips buffering?

Yep - importantly, I think `wrapAsyncIterator` here 

https://github.com/comunica/comunica/blob/6199e753efbe4d5658b5ef9ef500012525f093e3/packages/actor-rdf-resolve-quad-pattern-rdfjs-source/lib/RdfJsQuadSource.ts#L29

should become something like 

```ts
class IterableIterator extends AsyncIterator {
   constructor(source: Iterable<T>) {
      super();
      this.read = () => {
            let item;
            if (!(item = it.next()).done)
               return item.value
            return null
      }
   }
}

wrapAsyncIterator(it) {
    return new FastTransformIterator(new IterableIterator(it));
}
```

to take advantage of these recent changes https://github.com/rdfjs/N3.js/commit/d38dc45e0533317ce877f9346960ec6c885ef521

**Comment by rubensworks** [comment]
Should be resolved thanks to the changes in asynciterator.
